// vi:sw=4:ts=4

/* Copyright (c) 2013 Hello Inc. All Rights Reserved. */

#pragma once

#define BLE_UUID_HELLO_ALPHA0_SVC 0xBA5E
#define BLE_UUID_HELLO_ALPHA0_FROM_CENTRAL_CONFIRMED 0xDEED
#define BLE_UUID_HELLO_ALPHA0_FROM_BAND_CONFIRMED 0xD00D
#define BLE_UUID_HELLO_ALPHA0_FROM_BAND 0xFEED
#define BLE_UUID_HELLO_ALPHA0_FROM_CENTRAL 0xF00D

void hlo_ble_alpha0_init();
