/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.8 at Thu Oct 30 14:13:27 2014. */

#include "morpheus_ble.pb.h"



const pb_field_t wifi_endpoint_fields[5] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, wifi_endpoint, ssid, ssid, 0),
    PB_FIELD2(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, wifi_endpoint, bssid, ssid, 0),
    PB_FIELD2(  4, INT32   , REQUIRED, STATIC  , OTHER, wifi_endpoint, rssi, bssid, 0),
    PB_FIELD2(  5, ENUM    , REQUIRED, STATIC  , OTHER, wifi_endpoint, security_type, rssi, 0),
    PB_LAST_FIELD
};

const pb_field_t MorpheusCommand_fields[16] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, MorpheusCommand, version, version, 0),
    PB_FIELD2(  2, ENUM    , REQUIRED, STATIC  , OTHER, MorpheusCommand, type, version, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, deviceId, type, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, accountId, deviceId, 0),
    PB_FIELD2(  5, ENUM    , OPTIONAL, STATIC  , OTHER, MorpheusCommand, error, accountId, 0),
    PB_FIELD2(  6, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, wifiName, error, 0),
    PB_FIELD2(  7, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, wifiSSID, wifiName, 0),
    PB_FIELD2(  8, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, wifiPassword, wifiSSID, 0),
    PB_FIELD2(  9, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, batteryLevel, wifiPassword, 0),
    PB_FIELD2( 10, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, uptime, batteryLevel, 0),
    PB_FIELD2( 11, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, motionData, uptime, 0),
    PB_FIELD2( 12, BYTES   , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, motionDataEntrypted, motionData, 0),
    PB_FIELD2( 13, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, firmwareVersion, motionDataEntrypted, 0),
    PB_FIELD2( 14, MESSAGE , REPEATED, CALLBACK, OTHER, MorpheusCommand, wifi_scan_result, firmwareVersion, &wifi_endpoint_fields),
    PB_FIELD2( 15, ENUM    , OPTIONAL, STATIC  , OTHER, MorpheusCommand, security_type, wifi_scan_result, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
STATIC_ASSERT((pb_membersize(MorpheusCommand, wifi_scan_result) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_wifi_endpoint_MorpheusCommand)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
STATIC_ASSERT((pb_membersize(MorpheusCommand, wifi_scan_result) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_wifi_endpoint_MorpheusCommand)
#endif


